dist:     focal
sudo:     required  # используем Virtual Machine (а не Docker container)

language: cpp       # на практике разницы между специфичным для C++ окружением
# и, скажем, python -- никакой. Но пусть будет cpp.

os:
  - linux

compiler:
  - gcc
  - clang

script:
  # скрипт сборки и тестирования проекта:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd gtest
  - ./Google_Tests_run

deploy:
  # выкладываем tagged-коммиты на GitHub Releases:
  provider:     releases
  file:         <package-file>
  skip_cleanup: true
  overwrite:    true

  api_key:
    secure:   <encrypted-github-token>

  on:
    tags:     true