dist:     focal
sudo:     required  # используем Virtual Machine (а не Docker container)

language: cpp       # на практике разницы между специфичным для C++ окружением
# и, скажем, python -- никакой. Но пусть будет cpp.

os:
  - linux

compiler:
  - gcc
  - clang

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
  exclude:
    - os: linux
      compiler: gcc
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

    - os: linux
      compiler: gcc
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
  - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
  # скрипт сборки и тестирования проекта:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake --build .
  - ctest --output-on-failure

deploy:
  # выкладываем tagged-коммиты на GitHub Releases:
  provider:     releases
  file:         <package-file>
  skip_cleanup: true
  overwrite:    true

  api_key:
    secure:   <encrypted-github-token>

  on:
    tags:     true